title: >-
  Predicting water temperature in the Delaware River Basin: 3 Model configurations

abstract: >-
  This dataset includes Model parameters and metadata used to configure models.
  
cross-cites:
  -
    authors: ['Matthew R. Hipsey', 'Louise C. Bruce', 'Casper Boon', 'Brendan Busch', 'Cayelan C. Carey', 'David P. Hamilton', 'Paul C. Hanson', 'Jordan S. Read', 'Eduardo de Sousa', 'Michael Weber', 'Luke A. Winslow']
    title: >-
      A General Lake Model (GLM 3.0) for linking with high-frequency sensor data from the Global Lake Ecological Observatory Network (GLEON).
    pubdate: 2019
    form: publication
    link: https://doi.org/10.5194/gmd-12-473-2019
  -
    authors: ['XX']
    title: >-
      NLDAS XX
    pubdate: XX
    link: XX
    
entities:
  -
    data-name: reservoir_nml_list.rds
    data-description: 
    attributes:
    -
      attr-label: 
      attr-def: 
      attr-defs: 
      data-min: 
      data-max: 
      data-units: 
    -
    
build-environment: Multiple computer systems were used to generate these data, including XX. The open source languages R and Python was used on all systems, as well as XX.

process-date: !expr format(Sys.time(),'%Y%m%d')
indirect-spatial: U.S.A.
latitude-res: 0.1
longitude-res: 0.1
data-name: Model configuration details
data-description: >-
  Model configurations for running the General Lake Model (Hipsey et al. 2019) version 2 for each lake.
  The value for "lake_name" in the "morphometry" field is the mapping for "site_id" for the other datasets included in this release.

file-format: rds files.
