title: >-
  Predicting water temperature in the Delaware River Basin: 3 model configurations

abstract: >-
  This dataset includes Model parameters and metadata used to configure models.
  
cross-cites:
  -
    authors: ['XX']
    title: >-
      NLDAS XX
    pubdate: XX
    link: XX
    
entities:
  -
    data-name: res_nml_list.rds
    data-description: 
    attributes:
    -
      attr-label: 
      attr-def: 
      attr-defs: 
      data-min: 
      data-max: 
      data-units: 
    -
    
build-environment: Multiple computer systems were used to generate these data, including XX. The open source languages R and Python was used on all systems, as well as XX.

process-date: !expr format(Sys.time(),'%Y%m%d')
indirect-spatial: U.S.A.
latitude-res: 0.1
longitude-res: 0.1
data-name: 

file-format: rds files.


