title: >-
  Predicting water temperature in the Delaware River Basin: 3 Model configurations

abstract: >-
  This dataset includes Model parameters and metadata used to configure models.
  
cross-cites:
  -
    authors: ['Matthew R. Hipsey', 'Louise C. Bruce', 'Casper Boon', 'Brendan Busch', 'Cayelan C. Carey', 'David P. Hamilton', 'Paul C. Hanson', 'Jordan S. Read', 'Eduardo de Sousa', 'Michael Weber', 'Luke A. Winslow']
    title: >-
      A General Lake Model (GLM 3.0) for linking with high-frequency sensor data from the Global Lake Ecological Observatory Network (GLEON).
    pubdate: 2019
    form: publication
    link: https://doi.org/10.5194/gmd-12-473-2019
  -
    authors: ['XX']
    title: >-
      The General Lake Model - Configuration Options
    pubdate: XX
    link: https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
  -
    authors: ['XX']
    title: >-
      NLDAS XX
    pubdate: XX
    link: XX
    
entities:
  -
    data-name: reservoir_nml_list.rds
    data-description: list of reservoir parameters for input to GLM
    attributes:
    -
      attr-label: site-id
      attr-def:  >-
        Reservoir identification number for this dataset. Is the Prmnn_I from NHD high-res prefixed with source, as "nhdhr_{Prmnn_I}"
      attr-defs: NA
      data-min: NA
      data-max: NA
      data-units: NA
    -
      attr-label: cd
      attr-def: >-
        Bulk aerodynamic transfer coefficient for momentum
      attr-defs: >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: NA
    -
      attr-label: longitude
      attr-def: >-
        Longitude, positive East
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: decimal degrees
    -
      attr-label: latitude
      attr-def: >-
        Latitude, positive North
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: decimal degrees
    -
      attr-label: bsn_wid
      attr-def: >-
        Width of the lake basin, at crest height
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: meters
    -
      attr-label: bsn_len
      attr-def: >-
        Length of the lake basin, at crest height
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: meters
    -
      attr-label: lake_depth
      attr-def: >-
        Initial lake height/depth
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: meters
    -
      attr-label: max_layer_thick
      attr-def: >-
        Maximum thickness of a layer
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: meters
    -
      attr-label: min_layer_thick
      attr-def: >-
        Minimum thickness of a layer
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: meters
    -
      attr-label: meteo_fl
      attr-def: >-
        Filename of the meterological file
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: NA
    -
      attr-label: Kw
      attr-def: >-
        Light extinction coefficient
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: 1/meters
    -
      attr-label: A
      attr-def: >-
        Comma-separated list of lake areas
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: 
    -
      attr-label: H
      attr-def: >-
        Comma-separated list of lake elevations
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: 
    
build-environment: Multiple computer systems were used to generate these data, including XX. The open source languages R and Python was used on all systems, as well as XX.

process-date: !expr format(Sys.time(),'%Y%m%d')
indirect-spatial: U.S.A.
latitude-res: 0.1
longitude-res: 0.1
data-name: Model configuration details
data-description: >-
  Model configurations for running the General Lake Model (Hipsey et al. 2019) version 2 for each lake.
  The value for "lake_name" in the "morphometry" field is the mapping for "site_id" for the other datasets included in this release.

file-format: rds files.
