target_default: 3_config

include:

packages:
  - dplyr

sources:
  - src/fetch_filter_functions.R

targets:
  3_config:
    depends:
      - out_data/res_nml_list.rds
  
  ##### Transfer and filtering of files of file from lake-temperature-model-prep #####
  out_data/res_nml_list.rds:
    command: fetch_filter_nml(
      out_rds = target_name,
      in_ind = '../lake-temperature-model-prep/7_config_merge/out/nml_list.rds.ind',
      in_repo = I('../lake-temperature-model-prep/'),
      site_ids = reservoir_modeling_site_ids)